import { destinations } from './destinations.js';
const $=s=>document.querySelector(s); const slug=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const asArray=v=>{if(Array.isArray(v))return v;if(!v)return[];if(typeof v==='string'){try{const j=JSON.parse(v);if(Array.isArray(j))return j}catch{}return v.split('\n').map(x=>x.trim()).filter(Boolean)}return[]};
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const curated={
 lakshadweep:{name:'Lakshadweep',slug:'lakshadweep',region:'Agatti Island, Lakshadweep',duration:'4 days · 3 nights',image_url:'assets/images/package-posters/lakshadweep.jpg',summary:'An Agatti island escape with permit guidance, stay, meals, transfers and water activities.',description:'Experience Lakshadweep without planning stress. This four-day Agatti itinerary balances lagoon time, island sightseeing and optional adventures, with local support from landing to departure.',highlights:['Entry-permit assistance','Comfortable stay and stated meals','Airport pickup and drop','Island sightseeing','Snorkelling, kayaking and glass-bottom boat coordination'],itinerary:['Arrival, welcome drink, lunch, island sightseeing and dinner','Dolphin watch, lunch, snorkelling and island time','Optional scuba, kayaking and glass-bottom boat experience','Breakfast and airport transfer'],included:['Permit assistance','Accommodation','Meals listed in itinerary','Airport transfers','Island sightseeing','Local support'],excluded:['Flight tickets','Optional scuba diving','Banana boat ride','Night fishing','Personal expenses'],gallery:['assets/images/package-posters/lakshadweep.jpg','assets/images/island-beach.jpg','assets/images/scuba.jpg','assets/images/banana-boat.jpg']},
 kashmir:{name:'Kashmir',slug:'kashmir',region:'Srinagar · Gulmarg · Sonmarg · Pahalgam',duration:'5 days · 4 nights',image_url:'assets/images/package-posters/kashmir.jpg',summary:'A scenic Kashmir circuit with Srinagar, Gulmarg, Sonmarg and Pahalgam.',description:'See Kashmir through lake views, Mughal gardens, alpine roads and mountain valleys, with a comfortable route and dependable ground support.',highlights:['3 nights Srinagar and 1 night Pahalgam','One-hour Shikara ride','Gulmarg and Sonmarg excursions','Breakfast and dinner','Ground transport and support'],itinerary:['Srinagar arrival, gardens, temple and Shikara ride','Gulmarg excursion and optional seasonal activities','Sonmarg excursion and Srinagar stay','Transfer to Pahalgam via scenic stops','Breakfast and Srinagar Airport transfer'],included:['Airport transfers','Hotels as listed','Tempo Traveller','Daily breakfast and dinner','Shikara ride','Ground support'],excluded:['Union cabs','Gondola tickets','Lunch','Entry fees','Personal expenses'],gallery:['assets/images/package-posters/kashmir.jpg','assets/images/packages/kashmir.jpg']},
 umrah:{name:'Umrah Package',slug:'umrah',region:'Makkah & Madinah',duration:'15 days',featured:true,image_url:'assets/images/package-posters/umrah.jpg',summary:'A highlighted 15-day spiritual journey with accommodation, coordinated travel and guided support.',description:'Travel for Umrah with thoughtful guidance at every stage. This highlighted package supports a calm pilgrimage with accommodation options near key worship areas, coordinated transfers, assistance during the sacred rites and a team available throughout. Exact hotels, flights, meals and visa services are confirmed in the final quotation.',highlights:['15-day guided journey','Stay options near the Haram area','Makkah and Madinah coordination','Pre-departure document checklist','On-ground and WhatsApp support'],itinerary:['Arrival and transfer to Makkah','Guided preparation and performance of Umrah','Worship days and optional Makkah ziyarat','Transfer to Madinah','Worship and coordinated Madinah visits','Checkout and airport departure'],included:['Journey planning','Accommodation options','Makkah and Madinah transfers','Guided support','Selected ziyarat coordination','Document checklist'],excluded:['Airfare unless quoted','Visa and insurance unless stated','Meals not listed','Personal expenses','Services not in the final quote'],gallery:['assets/images/package-posters/umrah.jpg','assets/images/packages/umrah.jpg','assets/images/package-posters/umrah.jpg']},
 manali:{name:'Manali',slug:'manali',region:'Himachal Pradesh, India',duration:'5 days · 4 nights',image_url:'assets/images/package-posters/manali.jpg',summary:'Snow valleys, seasonal adventure sports and Himalayan scenery.',description:'A flexible mountain break built around Manali scenery, snow points, local sightseeing and seasonal adventure activities.',highlights:['Four nights and five days','Snow valleys','Seasonal activities','Hotel and transport choices','Local support'],itinerary:['Arrival and check-in','Local Manali sightseeing','Solang Valley','Flexible mountain excursion','Checkout and return'],included:['Hotel option','Breakfast option','Sightseeing','Selected transfers','Trip support'],excluded:['Travel to Manali unless quoted','Adventure activity fees','Entry fees','Unlisted meals','Personal expenses'],gallery:['assets/images/package-posters/manali.jpg','assets/images/packages/kashmir.jpg']}
};
async function getPackage(){const wanted=new URLSearchParams(location.search).get('slug')||'lakshadweep';try{const r=await fetch('/api/packages?slug='+encodeURIComponent(wanted));if(r.ok){const data=await r.json();return data.package}}catch{}if(curated[wanted])return curated[wanted];const found=destinations.find(x=>slug(x.name)===wanted)||destinations[0];return{name:found.name,slug:wanted,region:found.region,duration:found.days,image_url:found.fallback,summary:found.blurb,description:found.blurb,highlights:['Tailored itinerary','Stay and transfer options','WhatsApp support'],itinerary:['Arrival and transfer','Signature sightseeing','Local experience','Departure assistance'],included:['Trip planning','Selected transfers','Accommodation options','Local support'],excluded:['Personal expenses','Anything not confirmed in writing'],gallery:[found.fallback]}}
function render(p){const highlights=asArray(p.highlights),itinerary=asArray(p.itinerary),included=asArray(p.included),excluded=asArray(p.excluded||p.exclusions),gallery=asArray(p.gallery||p.gallery_images);const flight=typeof p.flight_details==='string'?JSON.parse(p.flight_details||'{}'):(p.flight_details||{}),room=typeof p.room_details==='string'?JSON.parse(p.room_details||'{}'):(p.room_details||{});document.title=`${p.name} — Bahadur Tours`;$('#package-detail').innerHTML=`
<section class="detail-hero"><img src="${safe(p.image_url||'assets/images/island-beach.jpg')}" alt="${safe(p.name)}"><div class="detail-shade"></div><div class="detail-hero-copy"><a href="booking.html">← All journeys</a><span>${safe(p.region||'Curated journey')} · ${safe(p.duration||'Flexible')}</span><h1>${safe(p.name)}</h1><p>${safe(p.summary||p.description)}</p><button class="btn btn-light" data-detail-book>Request this trip</button></div></section>
<section class="detail-facts section"><div><small>Duration</small><strong>${safe(p.duration||'Flexible')}</strong></div><div><small>Region</small><strong>${safe(p.region||'Custom route')}</strong></div><div><small>Starting price</small><strong>${safe(p.price||'Custom quote')}</strong></div><div><small>Support</small><strong>WhatsApp + local team</strong></div></section>
<section class="detail-story section"><div><span class="kicker">Complete package guide</span><h2>Know the journey<br><em>before you go.</em></h2><p>${safe(p.description||p.summary)}</p><ul>${highlights.map(x=>`<li>✓ ${safe(x)}</li>`).join('')}</ul></div><img src="${safe((gallery[1]||p.image_url||'assets/images/island-beach.jpg'))}" alt="Explore ${safe(p.name)}" loading="lazy"></section>
<section class="detail-itinerary section" id="detail-itinerary"><div class="section-head"><div><span class="kicker">Day by day</span><h2>Your itinerary.</h2></div><p>The final schedule is confirmed for your dates and services.</p></div><div class="itinerary-list">${itinerary.map((x,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><div><small>Day ${i+1}</small><h3>${safe(x)}</h3></div></article>`).join('')}</div></section>
<section class="detail-included section ${p.featured?'featured-package-section':''}"><div><span class="kicker">Package coverage</span><h2>Clear inclusions.<br><em>No surprises.</em></h2></div><div class="coverage-columns"><div><h3>Included</h3>${included.map(x=>`<span>✓ ${safe(x)}</span>`).join('')}</div><div class="exclusion-list"><h3>Not included</h3>${excluded.map(x=>`<span>— ${safe(x)}</span>`).join('')}</div></div></section>
${(flight.included||room.included)?`<section class="detail-arrangements section"><div><span class="kicker">Admin-confirmed options</span><h2>Travel arrangements.</h2></div><div class="arrangement-grid">${flight.included?`<article><small>Flight</small><h3>${safe(flight.airline||'Scheduled flight')} · ${safe(flight.cabin||'Economy')}</h3><p>${safe([flight.from,flight.to].filter(Boolean).join(' → '))}</p><span>${safe(flight.baggage||'As per airline policy')}</span></article>`:''}${room.included?`<article><small>Accommodation</small><h3>${safe(room.name||room.category||'Selected hotel')}</h3><p>${safe(room.room_type||'Room confirmed with booking')}</p><span>${safe(room.meals||room.city||'')}</span></article>`:''}</div></section>`:''}
<section class="detail-gallery section"><div class="section-head"><div><span class="kicker">Package gallery</span><h2>More images.</h2></div><p>Images added by the team are fetched automatically from the package manager.</p></div><div class="detail-photo-scroll">${(gallery.length?gallery:[p.image_url]).map((src,i)=>`<img src="${safe(src)}" alt="${safe(p.name)} image ${i+1}" loading="lazy">`).join('')}</div></section>
${p.terms?`<section class="section package-terms"><span class="kicker">Package terms</span><h2>Before you book.</h2><p>${safe(p.terms)}</p></section>`:''}`;window.currentPackage=p;document.querySelectorAll('[data-detail-book]').forEach(b=>b.onclick=()=>location.href='booking.html?trip='+encodeURIComponent(p.name))}
getPackage().then(render).catch(()=>{$('#package-detail').innerHTML='<section class="detail-loading">Package details could not be loaded.</section>'});
