import {db,requireAdmin,clean} from './_db.js';
const payload=(b:any)=>({name:clean(b.name,140),slug:clean(b.slug,160).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''),region:clean(b.region,180),category:clean(b.category,80),duration:clean(b.duration,80),price:clean(b.price,80),package_price:Number(b.package_price)||null,summary:clean(b.summary,500),description:clean(b.description,4000),image_url:b.image_url?String(b.image_url):'',latitude:Number(b.latitude)||null,longitude:Number(b.longitude)||null,highlights:Array.isArray(b.highlights)?b.highlights:[],itinerary:Array.isArray(b.itinerary)?b.itinerary:[],included:Array.isArray(b.included)?b.included:[],excluded:Array.isArray(b.excluded)?b.excluded:[],gallery:Array.isArray(b.gallery)?b.gallery:[],terms:clean(b.terms,3000),package_type:b.package_type==='international'?'international':'domestic',flight_details:b.flight_details||{},room_details:b.room_details||{},active:b.active!==false});
export default async function handler(req:any,res:any){try{const sql=db();
// Self-healing: add any columns that may be missing from older DB schemas
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_price NUMERIC`;
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS package_type TEXT NOT NULL DEFAULT 'domestic'`;
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS flight_details JSONB NOT NULL DEFAULT '{}'`;
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS room_details JSONB NOT NULL DEFAULT '{}'`;
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS gallery JSONB NOT NULL DEFAULT '[]'`;
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS terms TEXT`;
await sql`ALTER TABLE packages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ`;
if(req.method==='GET'){const slug=clean(req.query?.slug,160);if(slug){const rows=await sql`select * from packages where slug=${slug} and active=true limit 1`;return rows[0]?res.status(200).json({package:rows[0]}):res.status(404).json({error:'Package not found'})}if(String(req.query?.admin||'')==='1'){if(!requireAdmin(req,res))return;const rows=await sql`select * from packages order by created_at desc`;return res.status(200).json({packages:rows})}const rows=await sql`select * from packages where active=true order by created_at desc`;return res.status(200).json({packages:rows})}if(!requireAdmin(req,res))return;if(req.method==='POST'){const p=payload(req.body||{});if(!p.name||!p.slug)return res.status(400).json({error:'Name and slug are required'});const rows=await sql`insert into packages(name,slug,region,category,duration,price,package_price,summary,description,image_url,latitude,longitude,highlights,itinerary,included,excluded,gallery,terms,package_type,flight_details,room_details,active) values(${p.name},${p.slug},${p.region},${p.category},${p.duration},${p.price},${p.package_price},${p.summary},${p.description},${p.image_url},${p.latitude},${p.longitude},${JSON.stringify(p.highlights)}::jsonb,${JSON.stringify(p.itinerary)}::jsonb,${JSON.stringify(p.included)}::jsonb,${JSON.stringify(p.excluded)}::jsonb,${JSON.stringify(p.gallery)}::jsonb,${p.terms},${p.package_type},${JSON.stringify(p.flight_details)}::jsonb,${JSON.stringify(p.room_details)}::jsonb,${p.active}) returning *`;return res.status(201).json({package:rows[0]})}const id=clean(req.query?.id,80);if(!id)return res.status(400).json({error:'Package id is required'});if(req.method==='PUT'){const p=payload(req.body||{});const rows=await sql`update packages set name=${p.name},slug=${p.slug},region=${p.region},category=${p.category},duration=${p.duration},price=${p.price},package_price=${p.package_price},summary=${p.summary},description=${p.description},image_url=${p.image_url},latitude=${p.latitude},longitude=${p.longitude},highlights=${JSON.stringify(p.highlights)}::jsonb,itinerary=${JSON.stringify(p.itinerary)}::jsonb,included=${JSON.stringify(p.included)}::jsonb,excluded=${JSON.stringify(p.excluded)}::jsonb,gallery=${JSON.stringify(p.gallery)}::jsonb,terms=${p.terms},package_type=${p.package_type},flight_details=${JSON.stringify(p.flight_details)}::jsonb,room_details=${JSON.stringify(p.room_details)}::jsonb,active=${p.active},updated_at=now() where id=${id}::uuid returning *`;return res.status(200).json({package:rows[0]})}if(req.method==='DELETE'){await sql`delete from packages where id=${id}::uuid`;return res.status(200).json({ok:true})}return res.status(405).json({error:'Method not allowed'})}catch(error){if(error instanceof Error&&error.message.includes('packages_slug_key')){return res.status(400).json({error:'This URL slug is already in use. Please enter a unique slug.'})}return res.status(500).json({error:error instanceof Error?error.message:'Package request failed'})}}
